DROP TABLE IF EXISTS data_social CASCADE;


CREATE TABLE data_social(
    id_data int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un_text text
);


INSERT INTO data_social (un_text) VALUES ('Bonjour de la base de données :)');