DROP TABLE IF EXISTS data_social CASCADE;
DROP TABLE IF EXISTS account CASCADE;

CREATE TABLE account(
    username text PRIMARY KEY,
    password text
);
CREATE TABLE data_social(
    id_data int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un_text text,
    autor text REFERENCES account(username)
);

insert into account (username,password) values ('florian','ab4f63f9ac65152575886860dde480a1');